### ISSUE TITLE
sys-libs/dnf-plugins-core: reposync fails with SIGSEGV

### ISSUE THREAD

**Issue by ganto** [ganto/linuxmonk-overlay#14]
Since Jun 24 my `reposync` systemd timers occasionally fail with a SIGSEGV. E.g.:
```
# coredumpctl debug 1393165                                                                                                                          
           PID: 1393165 (reposync)                                      
           UID: 998 (reposync)     
           GID: 971 (reposync)               
        Signal: 11 (SEGV)
     Timestamp: Tue 2023-07-04 19:34:50 CEST (2min 27s ago)
  Command Line: /usr/bin/python3.11 /usr/bin/reposync --repofrompath fedora-37-aarch64,https://copr-be.cloud.fedoraproject.org/results/ganto/lxc4/fedora-37-aarch64/ --repo fedora-37-aarch64 --download-path /var/www/example.com/htdocs/packages/copr/mirror/ganto/lxc4
    Executable: /usr/bin/python3.11
 Control Group: /system.slice/system-reposync.slice/reposync@ganto-lxc4-fedora-37-aarch64.service
          Unit: reposync@ganto-lxc4-fedora-37-aarch64.service
         Slice: system-reposync.slice
       Boot ID: dba567e753a840a4b2bd156af4d70a08
    Machine ID: e92fb2b6cd686c1652e3aabc57ab9ea5
      Hostname: host.example.com
       Storage: /var/lib/systemd/coredump/core.reposync.998.dba567e753a840a4b2bd156af4d70a08.1393165.1688492090000000.zst (present)
  Size on Disk: 5.3M
       Message: Process 1393165 (reposync) of user 998 dumped core.

GNU gdb (Gentoo 13.2 vanilla) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://bugs.gentoo.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.11...
(No debugging symbols found in /usr/bin/python3.11)

warning: core file may not match specified executable file.
[New LWP 1393165]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/python3.11 /usr/bin/reposync --repofrompath fedora-37-aarch64,https://'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f38438d9476 in ?? () from /usr/lib64/libc.so.6
(gdb) bt
#0  0x00007f38438d9476 in ?? () from /usr/lib64/libc.so.6
#1  0x00007f38438916f2 in ?? () from /usr/lib64/libc.so.6
#2  0x00007f38438b031e in ?? () from /usr/lib64/libc.so.6
#3  0x00007f384231d485 in rpmlog () from /usr/lib64/librpmio.so.9
#4  0x00007f38421d5d00 in ?? () from /usr/lib64/libsqlite3.so.0
#5  0x00007f38421d5dd6 in sqlite3_log () from /usr/lib64/libsqlite3.so.0
#6  0x00007f38421f5176 in ?? () from /usr/lib64/libsqlite3.so.0
#7  0x00007f38421f5365 in ?? () from /usr/lib64/libsqlite3.so.0
#8  0x00007f38421f5404 in ?? () from /usr/lib64/libsqlite3.so.0
#9  0x00007f38422277b0 in ?? () from /usr/lib64/libsqlite3.so.0
#10 0x00007f38422bb9a8 in ?? () from /usr/lib64/libsqlite3.so.0
#11 0x00007f38401da392 in ?? () from /usr/lib/python3.11/lib-dynload/_sqlite3.cpython-311-x86_64-linux-gnu.so
#12 0x00007f3843b9a535 in ?? () from /usr/lib64/libpython3.11.so.1.0
#13 0x00007f3843b47498 in _PyObject_MakeTpCall () from /usr/lib64/libpython3.11.so.1.0
#14 0x00007f3843b84321 in ?? () from /usr/lib64/libpython3.11.so.1.0
#15 0x00007f3843b479de in PyObject_Vectorcall () from /usr/lib64/libpython3.11.so.1.0
#16 0x00007f3843b0005e in _PyEval_EvalFrameDefault () from /usr/lib64/libpython3.11.so.1.0
#17 0x00007f3843c0f63c in ?? () from /usr/lib64/libpython3.11.so.1.0
#18 0x00007f3843c0f6ed in PyEval_EvalCode () from /usr/lib64/libpython3.11.so.1.0
#19 0x00007f3843c4d203 in ?? () from /usr/lib64/libpython3.11.so.1.0
#20 0x00007f3843c4d3ed in ?? () from /usr/lib64/libpython3.11.so.1.0
#21 0x00007f3843c4d4b5 in ?? () from /usr/lib64/libpython3.11.so.1.0
#22 0x00007f3843c4fc50 in _PyRun_SimpleFileObject () from /usr/lib64/libpython3.11.so.1.0
#23 0x00007f3843c50172 in _PyRun_AnyFileObject () from /usr/lib64/libpython3.11.so.1.0
#24 0x00007f3843c6b453 in Py_RunMain () from /usr/lib64/libpython3.11.so.1.0
#25 0x00007f3843c6b9ef in Py_BytesMain () from /usr/lib64/libpython3.11.so.1.0
#26 0x00007f384385e93b in ?? () from /usr/lib64/libc.so.6
#27 0x00007f384385e9e7 in __libc_start_main () from /usr/lib64/libc.so.6
#28 0x000055b4c927f081 in _start ()
```
On Jun 24 the following involved packages were updated:
* dev-db/sqlite-3.41.2-r1 -> 3.42.0
* dev-lang/python-3.11.3 -> 3.11.4
* sys-apps/dnf-4.15.1 -> 4.15.1-r1

The `sys-apps/dnf` update only added a symlink for `/usr/bin/dnf-3` so I suspect the issue to be somewhere between Python and sqlite...

**Comment by ganto** [comment]
Issue seems not to happen any longer. Not sure what fixed it...
